# Generated by Django 4.1.3 on 2022-11-30 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('ApellidosP', models.CharField(max_length=100)),
                ('ApellidosM', models.CharField(max_length=100)),
                ('FechaNac', models.DateField()),
                ('Genero', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Seleccionar', max_length=20)),
                ('Edad', models.IntegerField()),
                ('Foto', models.ImageField(blank=True, upload_to='poster/')),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=300)),
                ('Telefono', models.CharField(max_length=10)),
                ('HorarioApertura', models.TimeField()),
                ('HorarioCierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('FechaCreacion', models.DateField()),
                ('Logo', models.ImageField(blank=True, upload_to='poster/')),
                ('Ubicacion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroLiterario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('NumSerie', models.IntegerField()),
                ('Precio', models.IntegerField()),
                ('Portada', models.ImageField(blank=True, upload_to='poster/')),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.autor')),
                ('Biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.biblioteca')),
                ('Editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.editorial')),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.generoliterario')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
                ('NombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
